-- Customer account snapshot table. One import date represents one source snapshot.
CREATE TABLE IF NOT EXISTS customer_account (
  id BIGINT NOT NULL AUTO_INCREMENT,
  marketing_platform VARCHAR(100) NULL,
  contract_sign_customer VARCHAR(200) NULL,
  final_user_customer VARCHAR(200) NULL,
  annual_ops_fee DECIMAL(18,2) NULL,
  business_category VARCHAR(50) NULL,
  is_in_target VARCHAR(10) NULL,
  service_expire_date DATE NULL,
  sign_progress VARCHAR(50) NULL,
  contract_code VARCHAR(100) NULL,
  item_code VARCHAR(100) NULL,
  province VARCHAR(50) NULL,
  city VARCHAR(50) NULL,
  district VARCHAR(50) NULL,
  ops_item VARCHAR(100) NULL,
  env_project_name VARCHAR(200) NULL,
  customer_type VARCHAR(50) NULL,
  sales_dept VARCHAR(200) NULL,
  sales_person VARCHAR(50) NULL,
  unsigned_category VARCHAR(50) NULL,
  exclude_reason_category VARCHAR(50) NULL,
  exclude_reason_desc VARCHAR(500) NULL,
  contract_name VARCHAR(500) NULL,
  contract_apply_date DATE NULL,
  contract_type VARCHAR(50) NULL,
  archive_status VARCHAR(50) NULL,
  is_virtual VARCHAR(10) NULL,
  ops_start_date DATE NULL,
  ops_end_date DATE NULL,
  detail_amount DECIMAL(18,2) NULL,
  expected_revenue DECIMAL(18,2) NULL,
  expected_collection DECIMAL(18,2) NULL,
  actual_revenue DECIMAL(18,2) NULL,
  actual_collection DECIMAL(18,2) NULL,
  acceptance_date DATE NULL,
  contract_count INT NULL,
  payment_method VARCHAR(50) NULL,
  contact_person VARCHAR(50) NULL,
  contact_phone VARCHAR(100) NULL,
  communication_detail VARCHAR(500) NULL,
  remark VARCHAR(500) NULL,
  create_date VARCHAR(8) NOT NULL,
  imported_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id, create_date),
  KEY idx_contract_code (contract_code),
  KEY idx_item_code (item_code),
  KEY idx_sign_customer (contract_sign_customer),
  KEY idx_final_user (final_user_customer),
  KEY idx_province_city (province, city),
  KEY idx_create_date (create_date),
  KEY idx_service_expire (service_expire_date),
  KEY idx_sales_dept (sales_dept)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
PARTITION BY RANGE COLUMNS(create_date) (
  PARTITION p_future VALUES LESS THAN (MAXVALUE)
);
