-- ERP 数据表（新旧ERP合并数据）
CREATE TABLE IF NOT EXISTS erp_data (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  seq_no INT NULL COMMENT '原始行号',
  contract_id VARCHAR(50) NOT NULL COMMENT '合同编号',
  sales_org VARCHAR(200) NULL COMMENT '销售组织',
  is_initialized VARCHAR(10) NULL COMMENT '是否初始化',
  contract_name VARCHAR(500) NULL COMMENT '合同名称',
  contract_apply_date DATE NULL COMMENT '合同申请日期',
  sales_dept VARCHAR(200) NULL COMMENT '销售业绩部门',
  applicant VARCHAR(50) NULL COMMENT '申请人',
  sales_person VARCHAR(50) NULL COMMENT '销售员',
  sign_customer VARCHAR(200) NULL COMMENT '签约客户',
  final_customer VARCHAR(200) NULL COMMENT '最终客户',
  third_party VARCHAR(200) NULL COMMENT '第三方',
  contract_type VARCHAR(50) NULL COMMENT '合同类型',
  is_estimated_ops VARCHAR(10) NULL COMMENT '暂估运维运营',
  is_virtual VARCHAR(10) NULL COMMENT '虚拟合同',
  is_2026_saas_renew VARCHAR(10) NULL COMMENT '2026运维saas续签',
  doc_status VARCHAR(50) NULL COMMENT '单据状态',
  close_status VARCHAR(50) NULL COMMENT '关闭状态',
  exec_status VARCHAR(50) NULL COMMENT '合同执行状态',
  archive_status VARCHAR(50) NULL COMMENT '归档状态',
  archive_date DATE NULL COMMENT '归档日期',
  total_amount DECIMAL(18,2) NULL COMMENT '合同总金额',
  free_ops_months INT NULL COMMENT '免费运维期（月）',
  annual_ops_amount DECIMAL(18,2) NULL COMMENT '年运维约定金额',
  city VARCHAR(50) NULL COMMENT '城市',
  province VARCHAR(50) NULL COMMENT '省份',
  sales_contract_detail_id VARCHAR(100) NULL COMMENT '销售合同明细id',
  item_code VARCHAR(100) NULL COMMENT '标的行编码',
  item_name VARCHAR(500) NULL COMMENT '标的',
  business_type VARCHAR(100) NULL COMMENT '业务类型',
  project_code VARCHAR(100) NULL COMMENT '交付项目编码',
  project_name VARCHAR(500) NULL COMMENT '交付项目',
  ops_sign_type VARCHAR(100) NULL COMMENT '运维签约类型',
  detail_qty INT NULL COMMENT '明细数量',
  unit_price DECIMAL(18,2) NULL COMMENT '销售单价',
  detail_amount_with_tax DECIMAL(18,2) NULL COMMENT '明细价税合计',
  ops_start_date DATE NULL COMMENT '运维开始日期',
  ops_end_date DATE NULL COMMENT '运维结束日期',
  exec_detail_id VARCHAR(100) NULL COMMENT '执行明细id',
  product_material VARCHAR(500) NULL COMMENT '产品物料',
  product_ratio VARCHAR(50) NULL COMMENT '产品占比',
  cloud_service_type VARCHAR(50) NULL COMMENT '云服务类型',
  product_amount DECIMAL(18,2) NULL COMMENT '产品金额',
  product_line1 VARCHAR(100) NULL COMMENT '一级产品线',
  product_line2 VARCHAR(100) NULL COMMENT '二级产品线',
  product_company VARCHAR(200) NULL COMMENT '产品公司',
  division VARCHAR(100) NULL COMMENT '所属事业部',
  cum_billing DECIMAL(18,2) NULL COMMENT '累计开票金额',
  cum_collection DECIMAL(18,2) NULL COMMENT '累计回款金额',
  cum_revenue DECIMAL(18,2) NULL COMMENT '累计确收金额',
  cur_year_billing DECIMAL(18,2) NULL COMMENT '当年开票金额',
  prev_year_billing DECIMAL(18,2) NULL COMMENT '去年同期开票金额',
  cur_year_collection DECIMAL(18,2) NULL COMMENT '当年回款金额',
  prev_year_collection DECIMAL(18,2) NULL COMMENT '去年同期回款金额',
  cur_year_revenue DECIMAL(18,2) NULL COMMENT '当年收入金额',
  prev_year_revenue DECIMAL(18,2) NULL COMMENT '去年同期收入金额',
  cur_year_amort DECIMAL(18,2) NULL COMMENT '当年应分摊金额',
  prev_year_amort DECIMAL(18,2) NULL COMMENT '去年同期应分摊金额',
  sales_platform VARCHAR(100) NULL COMMENT '营销平台',
  system_engineer VARCHAR(50) NULL COMMENT '体系工程师',
  is_public_cloud VARCHAR(10) NULL COMMENT '是否公有云',
  is_one_time_revenue VARCHAR(10) NULL COMMENT '是否一次性收入',
  contract_category VARCHAR(50) NULL COMMENT '合同分类',
  business_category VARCHAR(50) NULL COMMENT '业务类别',
  other_business_type VARCHAR(50) NULL COMMENT '其他业务类型',
  invalid_contract_type VARCHAR(50) NULL COMMENT '无效合同类型',
  data_source VARCHAR(50) NULL COMMENT '数据来源',
  create_date VARCHAR(8) NOT NULL COMMENT '数据日期',
  contract_days INT NULL COMMENT '合同天数',
  prev_year_period_start DATE NULL COMMENT '去年统计起始日期',
  prev_year_period_end DATE NULL COMMENT '去年统计截止日期',
  prev_year_calc_amort DECIMAL(18,2) NULL COMMENT '去年按期间分摊服务费',
  prev_year_adjusted_amort DECIMAL(18,2) NULL COMMENT '去年倒签调整后分摊服务费',
  cur_year_period_start DATE NULL COMMENT '今年统计起始日期',
  cur_year_period_end DATE NULL COMMENT '今年统计截止日期',
  cur_year_calc_amort DECIMAL(18,2) NULL COMMENT '今年按期间分摊服务费',
  cur_year_adjusted_amort DECIMAL(18,2) NULL COMMENT '今年倒签调整后分摊服务费',
  file_source_date VARCHAR(20) NULL COMMENT '文件来源日期',
  imported_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '入库时间',
  PRIMARY KEY (id, create_date),
  UNIQUE KEY uk_snapshot_line (contract_id, item_code, exec_detail_id, create_date),
  INDEX idx_province_city (province, city),
  INDEX idx_contract_type (contract_type),
  INDEX idx_sales_dept (sales_dept),
  INDEX idx_product_line (product_line1, product_line2),
  INDEX idx_data_source (data_source),
  INDEX idx_create_date (create_date),
  INDEX idx_contract_date (contract_apply_date),
  INDEX idx_doc_status (doc_status),
  INDEX idx_final_customer (final_customer)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ERP合同数据'
PARTITION BY RANGE COLUMNS(create_date) (
  PARTITION p_future VALUES LESS THAN (MAXVALUE)
);
