CREATE TABLE IF NOT EXISTS ops_service_revenue_monthly (
  stat_year SMALLINT NOT NULL COMMENT '统计年',
  stat_month TINYINT NOT NULL COMMENT '统计月',
  sales_platform VARCHAR(100) NOT NULL COMMENT '营销平台',
  erp_create_date VARCHAR(8) NOT NULL COMMENT 'ERP快照日期',
  revenue_target DECIMAL(18,2) NOT NULL COMMENT '收入目标值（元）',
  recognized_revenue DECIMAL(18,2) NOT NULL COMMENT '确收完成值（元）',
  revenue_completion_rate DECIMAL(18,6) NULL COMMENT '收入完成率',
  contracts_on_hand_amount DECIMAL(18,2) NOT NULL COMMENT '在手合同额（元）',
  prior_year_contracts_on_hand_amount DECIMAL(18,2) NOT NULL COMMENT '去年同期在手合同额（元）',
  contracts_on_hand_yoy_amount DECIMAL(18,2) NOT NULL COMMENT '在手合同同比增长值（元）',
  contracts_on_hand_yoy_rate DECIMAL(18,6) NULL COMMENT '在手合同同比增长率',
  recognized_revenue_excluding_estimate DECIMAL(18,2) NOT NULL COMMENT '不含暂估确收值（元）',
  prior_year_recognized_revenue DECIMAL(18,2) NOT NULL COMMENT '去年同期确收值（元）',
  recognized_revenue_yoy_amount DECIMAL(18,2) NOT NULL COMMENT '确收同比增长值（元）',
  recognized_revenue_yoy_rate DECIMAL(18,6) NULL COMMENT '确收同比增长率',
  signing_completed_amount DECIMAL(18,2) NOT NULL COMMENT '签约完成值（元）',
  prior_year_signing_amount DECIMAL(18,2) NOT NULL COMMENT '去年同期签约值（元）',
  signing_yoy_amount DECIMAL(18,2) NOT NULL COMMENT '签约同比增长值（元）',
  signing_yoy_rate DECIMAL(18,6) NULL COMMENT '签约同比增长率',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (stat_year, stat_month, sales_platform),
  KEY idx_erp_create_date (erp_create_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='运维服务月度营收统计表';
